# Generated by Django 4.2.1 on 2023-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_rename_user_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
