# Generated by Django 4.2.1 on 2023-07-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_servicesuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesuser',
            name='update_date',
        ),
        migrations.AddField(
            model_name='servicesuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
