# Generated by Django 4.2.1 on 2023-07-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_servicesuser_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesuser',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
