# Generated by Django 4.2.1 on 2023-07-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_servicesuser_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicesUser',
        ),
    ]
